version = "0.1"

[assemblers]
gas = true
nasm = false
go = false
z80 = false
masm = false

[instruction_sets]
arm = true
riscv = false
x86 = false
x86_64 = false
z80 = false

[opts]
compiler = "zig"
diagnostics = true
default_diagnostics = true
