define o: file
o{*} : extension = o

define asm: file
asm{*}: extension = asm

builddir = ./build/


import! ld=ld%exe{ld}
import! as=as%exe{as}


$builddir/exe{hello_world}: $builddir/o{hello_world} $ld
{{
	  diag ld -o $>  ($<[0])
		$ld $path($<[0]) -o "$path($>[0])"
}}

exe{hello_world}:$builddir/exe{hello_world}: backlink=true


$builddir/o{hello_world}:  asm{*} $as
{{
	diag as -o $> ($<[0])
	$as $path($<[0]) -o $path($>[0])
}}

./: fsdir{$builddir} exe{hello_world}
